services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      retries: 10

  test_runner:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql+psycopg2://test_user:test_pass@postgres:5432/test_db
    command: pytest --tb=short --disable-warnings
    volumes:
      - .:/crud_pytest
    working_dir: /crud_pytest

volumes:
  pgdata: